solace:
  event.portal.endpoint: https://api.solace.cloud
  event.portal.token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1hYXNfcHJvZF8yMDIwMDMyNiIsInR5cCI6IkpXVCJ9.eyJvcmciOiJzZWFsbCIsIm9yZ1R5cGUiOiJFTlRFUlBSSVNFIiwic3ViIjoienBmc2YxeDR2b3oiLCJwZXJtaXNzaW9ucyI6IkFBQUFBSUFQQUFBQWZ6Z0E0QUVBQUFBQUFBQUFBQUFBQUlDeHpvY2hJQWpnTC8vL2c1WGZCZDREV1BNRDY0ZS9Qdz09IiwiYXBpVG9rZW5JZCI6ImV0Zmh1em1zNGN6IiwiaXNzIjoiU29sYWNlIENvcnBvcmF0aW9uIiwiaWF0IjoxNjc0NzM1OTA3fQ.mQJ3uhTH190BWR1gSGxMzs9PotOyrFuqhZUgNf-a1fg8fgaQG4d4oncOfpcjRYxe9De2nW17du2D9nQXp_uDTNc_L2U5NglNNHrIdOdDFKxoKx23TfNl9-514NkT99bwtR7V9NHmeDZq58DTGekkjdCUYtibaXX0LSzNmU7jl6q2fxY_ypdO5T0Unt2lzzPsq00WJqJ5fSWm_3fp5GgGAHJaRDV6w3w-yHDMV4gu-1Qxb_JLlhhAROWVxMpXqAmh_xGjfiqKRzvt140nhBzMcg9ZsEAaj2hkrTmKcVSscidJfo6Nch--peVtKYjdcbHw3jveG89_xnGrM_FHo4SKOA
  event.transformer.crypto-shredder.sourceEventVersionId: u0bk1wbfken
  event.transformer.crypto-shredder.targetEventVersionId: bpdhmh9n62w
  event.transformer.crypto-shredder.vaultTransitEncryptionKey: customer
spring:
  cloud:
    function:
      definition: eventToDTOConverter
    stream:
      solace:
        default:
          consumer:
            provisionDurableQueue: true
            addDestinationAsSubscriptionToQueue: true
      bindings:
        eventToDTOConverter-in-0:
          destination: ef/cdm/idm/customer/account/created/v1/>
          group: customerAccountCreatedEventGroup
          contentType: application/json
          binder: solace-binder
        eventToDTOConverter-out-0:
          destination: ef/cdm/idm/customer/account/created/dto
          binder: solace-binder
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'tcps://mr-connection-1g9rk2quv44.messaging.solace.cloud:55443'
                msgVpn: ernstings-family-azure
                clientUsername: solace-cloud-client
                clientPassword: p9sg2soblsnbl753iqopudcs60
    vault:
      host: 192.168.100.140
      port: 8200
      scheme: http
      uri: http://192.168.100.140:8200
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: hvs.hVvmecs6WLriomvtlWRFXYFC
      fail-fast: true
      config:
        lifecycle:
          enabled: true
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: '*'